name: Deploy to Cloud Run

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Image version to deploy"
        required: true

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west1
  SERVICE_NAME: wanikani-service
  REPOSITORY: wanikani-relearn
  IMAGE_NAME: wanikanirelearn

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Add permissions for WIF if you switch to it
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER_ID }}
          service_account: 'github-actions-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'
          token_format: 'access_token'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image=$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.event.inputs.version }} \
            --region=$REGION \
            --platform=managed \
            --allow-unauthenticated \
            --labels=managed-by=github-actions,version=${{ github.event.inputs.version }} \
            --quiet